---
title: "Forecasting Tools Basics"
output:
  html_document:
    df_print: paged
date: "February 19, 2019"
---

```{r loadpackages, message=FALSE, warning=FALSE}
library(fpp2)
library(dplyr)
library(GGally)
library(gridExtra)  ## Generate multiple figures in one chart

theme_set(theme_classic())
```

__Time Plots:__
```{r timeplots}
  # Example Time Plots from "fpp2 package"
data(package = "fpp2")

  # weekly passenger load between Melbourne and Sydney
data(melsyd)  
  autoplot(melsyd[,"Economy.Class"]) +
    ggtitle("Economy class passengers: Melbourne to Sydney") +
    xlab("Year") + ylab("Thousands") 

  # monthly anti-diabetic drug sales 
data(a10)  
autoplot(a10) +
  ylab("$ million") + xlab("Year") +
  ggtitle("Antidiabetic Drug Sales")
```
__Season Plots:__
```{r seasonplots}
ggseasonplot(a10, year.labels = TRUE) +
  ylab("$ million") +
  ggtitle("Seasonal plot: antidiabetic drug sales")

 # Polar seasonal plot
ggseasonplot(a10, polar=TRUE) +
  ylab("$ million") +
  ggtitle("Polar seasonal plot: antidiabetic drug sales")
```

__Subseries Plot (y vs. year, by month):__
```{r subseriesplot}
ggsubseriesplot(a10) +
  ylab("$ million") +
  ggtitle("Seasonal subseries plot: antidiabetic drug sales")
```

__Scatterplot Matrix:__
```{r scatterplotmatrix, warning=FALSE, message=FALSE}
visnights[,1:5] %>% as.data.frame() %>% GGally::ggpairs()
```

__Correlogram showing Autocorrelation Function:__
```{r ACF}
beer2 <- window(ausbeer, start=1992)

gglagplot(beer2)

ggAcf(beer2) #https://afit-r.github.io/ts_exploration#

  
# Example with Trend and Seasonality
aelec <- window(elec, start=1980)
autoplot(aelec) + xlab("Year") + ylab("GWh")
ggAcf(aelec, lag= 48)
```
  
__Simple Forecasting Methods__
```{r forecastMethods, results='hide'}
  # Set training data from 1992 to 2007
beer2 <- window(ausbeer, start=c(1992,1), end=c(2007,4))

  # Average Method
meanf(beer2, h=10)
  
  # Naive Method
naive(beer2, h=50)

  # Seasonal Naive
snaive(beer2, h=11)

  # Drift Method
rwf(beer2, h=11, drift = TRUE)

  # Plot some forecasts
autoplot(beer2) +
  autolayer(meanf(beer2, h=11),
            series="Mean", PI=FALSE) +
  autolayer(naive(beer2, h=11),
            series="Naive", PI=FALSE) +
  autolayer(snaive(beer2, h=11),
            series="Seasonal naive", PI=FALSE) +
  ggtitle("Forecasts for quarterly beer production") +
  xlab("Year") + ylab("Megalitres") +
  guides(color=guide_legend(title="Forecast"))
```

__Example of Mathematical Transformations:__
```{r Transformations}
  # Box-Cox Transformation
(lambda <- BoxCox.lambda(elec))

autoplot(BoxCox(elec,lambda)) +
  theme_classic() +
  ggtitle("Box-Cox transformed antidiabetic drug sales")


  # Another example
p1 <- autoplot(a10) +
  ylab("$ million") + xlab("Year") +
  ggtitle("Antidiabetic drug sales")

(lambda <- BoxCox.lambda(a10))
p2 <- autoplot(BoxCox(a10,lambda)) +
  xlab("Year") +  ylab("$ million") +
  ggtitle("Box-Cox transformed antidiabetic drug sales")

grid.arrange(p1, p2, nrow=2)
```

__Bias Adjustments:__
```{r biasAdjustments}
fc <- rwf(eggs, drift=TRUE, lambda=0, h=50, level=80)
fc2 <- rwf(eggs, drift=TRUE, lambda=0, h=50, level=80,
           biasadj=TRUE)
autoplot(eggs) +
  autolayer(fc, series="Simple back transformation") +
  autolayer(fc2, series="Bias adjusted", PI=FALSE) +
  guides(color=guide_legend(title="Forecast"))
```

__Forecast Accuracy:__
```{r forecastAccuracy}
  # Forecasts
beer2 <- window(ausbeer,start=1992,end=c(2007,4))
beerfit1 <- meanf(beer2,h=10)
beerfit2 <- rwf(beer2,h=10)
beerfit3 <- snaive(beer2,h=10)
autoplot(window(ausbeer, start=1992)) +
  autolayer(beerfit1, series="Mean", PI=FALSE) +
  autolayer(beerfit2, series="Naive", PI=FALSE) +
  autolayer(beerfit3, series="Seasonal naive", PI=FALSE) +
  xlab("Year") + ylab("Megalitres") +
  ggtitle("Forecasts for quarterly beer production") +
  guides(color=guide_legend(title="Forecast"))

  # Forecast accuracy (using Test data)
beer3 <- window(ausbeer, start=2008)
accuracy(beerfit1, beer3)
accuracy(beerfit2, beer3)
accuracy(beerfit3, beer3)
```

__Prediction Invtervals:__
```{r predictionInterval}
naive(goog200)

autoplot(naive(goog200)) + 
  xlab("Day") +
  ylab("Closing Price (US$)") +
  ggtitle("Forecast of Google Stock Price\nPrediction Interval")

res <- residuals(naive(goog200))

autoplot(res) +
  xlab("Day") +
  ylab("") +
  ggtitle("Residuals from naive method")

gghistogram(res) +
  ggtitle("Histogram of residuals")

ggAcf(res) +
  ggtitle("ACF of residuals")

checkresiduals(naive(goog200))
```

